# Builder
FROM golang:1.21.3-alpine as builder
RUN apk add --no-cache git
ARG PROJECT_PATH="/telegram-bot-main"
ARG BUILD_PATH="/build/bot"
COPY go.mod $PROJECT_PATH/
COPY go.sum $PROJECT_PATH/
COPY .env.dev $PROJECT_PATH/
COPY .env.prod $PROJECT_PATH/
COPY .env.test $PROJECT_PATH/
RUN cd $PROJECT_PATH && go mod download
ADD . $PROJECT_PATH
RUN cd $PROJECT_PATH && go build -o .$BUILD_PATH/bot

# Final
FROM alpine:latest
ARG RESOURCE_PATH="/resource"
ARG PROJECT_PATH="/telegram-bot-main"
ARG BUILD_PATH="/build/bot"
COPY --from=builder $PROJECT_PATH$BUILD_PATH/bot /usr/local/bin/
COPY --from=builder $PROJECT_PATH/.env.dev /
COPY --from=builder $PROJECT_PATH/.env.prod /
COPY --from=builder $PROJECT_PATH/.env.test /
CMD ["/usr/local/bin/bot"]
