version: "3.8"


services:
  telegram-bot-main:
    build:
      context: ./telegram-bot-main
      dockerfile: ./dockerfile
    image: telegram-bot-main
    container_name: telegram-bot-main
    volumes:
      - main-data:/var/lib/telegram-bot-data/data
    environment:
      TELEGRAM_API_TOKEN: 6567872276:AAHEAECnF_1hLhV2f8_FKwEs_aHuh6WlREw
      DATABASE_HOST: telegram-bot-postgres
      CACHE_HOST: telegram-bot-redis
      TELEGRAM_BOT_MODE: prod
    depends_on:
      - telegram-bot-postgres
      - telegram-bot-pgadmin
  telegram-bot-postgres:
    build:
      context: ./telegram-bot-postgres
      dockerfile: ./dockerfile
    image: telegram-bot-postgres
    container_name: telegram-bot-postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"
  telegram-bot-pgadmin:
    image: dpage/pgadmin4
    container_name: telegram-bot-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8888:80/tcp"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
    depends_on:
      - telegram-bot-postgres
  telegram-bot-redis:
    image : redis:latest
    container_name: telegram-bot-redis
    restart: always
    ports:
      - "6379:6379/tcp"
volumes:
  main-data:
  postgres-data:
  pgadmin-data:
