version: "1.0.0"
services:
  telegram-bot-postgres:
    build:
      context: ./telegram-bot-postgres
    image: telegram-bot-postgres
    container_name: telegram-bot-postgres
    restart: always
    volumes:
      - postgres-data:${PGDATA}
    ports:
      - 5432:5432/tcp
    networks:
      postgres-network:
        ipv4_address: ${NETWORK_POSTGRES}
  telegram-bot-pgadmin:
    image: dpage/pgadmin4
    container_name: telegram-bot-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 8888:80/tcp
    volumes:
      - pgadmin-data:${PGADMIN_DATA}
    links:
      - "telegram-bot-postgres:pgsql-server"
  telegram-bot-main:
    build:
      context: ./telegram-bot-main
    image: telegram-bot-main
    container_name: telegram-bot-main
    volumes:
      - main-data:${TELEGRAM_BOT_DATA}
    environment:
      - DATABASE_HOST=${NETWORK_POSTGRES}
networks:
  postgres-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

volumes:
  main-data:
  postgres-data:
  pgadmin-data:
