version: "1.0.0"
services:
  telegram-bot-main:
    build:
      context: ./telegram-bot-main
      dockerfile: ./dockerfile
    image: telegram-bot-main
    container_name: telegram-bot-main
    volumes:
      main-data: /var/lib/telegram-bot-data/data
    environment:
      DATABASE_HOST: telegram-bot-postgres
      TELEGRAM_BOT_MODE: prod
    links:
      - telegram-bot-postgres
  telegram-bot-postgres:
    build:
      context: ./telegram-bot-postgres
      dockerfile: ./dockerfile
    image: telegram-bot-postgres
    container_name: telegram-bot-postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      postgres-data: /var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
  telegram-bot-pgadmin:
    image: dpage/pgadmin4
    container_name: telegram-bot-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 8888:80/tcp
    volumes:
      pgadmin-data: /var/lib/pgadmin/data
    links:
        - telegram-bot-postgres
volumes:
  main-data:
  postgres-data:
  pgadmin-data:
