FROM golang:1.21-alpine as builder
RUN apk add --no-cache gcc musl-dev linux-headers git
ENV MAIN_NAME="bot"
ENV PROJECT_PATH="/telegram-bot-sample1"
ENV BUILD_PATH="/build/bot"
COPY go.mod $PROJECT_PATH/
COPY go.sum $PROJECT_PATH/
RUN cd $PROJECT_PATH && go mod download
ADD . $PROJECT_PATH
RUN cd $PROJECT_PATH && go build -o .$BUILD_PATH/$MAIN_NAME

FROM alpine:latest
RUN apk add --no-cache ca-certificates
ENV MAIN_NAME="bot"
ENV PROJECT_PATH="/telegram-bot-sample1"
ENV BUILD_PATH="/build/bot"
COPY --from=builder $PROJECT_PATH$BUILD_PATH/$MAIN_NAME /usr/local/bin/